### ISSUE TITLE
Some CA Policies missing in the export

### ISSUE THREAD

**Issue by zupermik** [microsoft/EntraExporter#35]
Greetings!

Unfortunately, one of my two CA policies were missing in the export. I have a really small test environment for tests where I am looking into the azureadexporter.

I tried with -All as well as "-Type "ConditionalAccess" and default with same result.

Thanks for a cool and needed exporter!

**Comment by merill** [comment]
@zupermik can you share some details on the CA policy that you created which is not being exported?

**Comment by BT-ITA-Olaf** [comment]
Hi,

We are facing the same issue. Our missing policy has all the users, all the cloud apps, four conditions  and grant MFA + compliant device. Any update on how to fix it? 

Thank you!

**Comment by merill** [comment]
The export is using the v1 endpoint but it looks like a recent change to the API is excluding certain policies from v1 if they are using beta features. I'll release a fix soon to switch to the beta endpoint (and also make it a config option).

**Comment by zupermik** [comment]
@merill Thanks!

**Comment by admingashvmb** [comment]
@merill Is this issue fixed?

**Comment by merill** [comment]
Very sorry about the delay in this folks. The issue has been fixed. Please download the new EntraExporter module
