### ISSUE TITLE
Cannot find LinkedIn account connections

### ISSUE THREAD

**Issue by qwertguy** [microsoft/EntraExporter#36]
Is It possible to pull the value of LinkedIn account connections?

You can find it under Azure Active Directory -> Users -> Manage -> User settings.

![image](https://user-images.githubusercontent.com/38832691/197505408-383157ba-0d2a-4b56-ace9-7a847d8adbe0.png)

**Comment by merill** [comment]
Unfortunately this setting is not yet available in Graph API.
