### ISSUE TITLE
Cannot find Show option to remain signed in

### ISSUE THREAD

**Issue by qwertguy** [microsoft/EntraExporter#37]
Is it possible to show the option to remain signed in?

It is under Azure Active Directory -> Company Branding 

When pulling `Export-AzureAD -Path 'C:\AzureADBackup2\' -Type "Organization"` I receive branding information but **Show option to remain signed in** is not included. 

Do you know how I can receive this information?

Thanks 
![image](https://user-images.githubusercontent.com/38832691/197506039-612c5b75-6043-4f0d-86ac-c81ef7e63b2b.png)

**Comment by merill** [comment]
Unfortunately there is no Graph API available for this setting right now.
