### ISSUE TITLE
Consistent backup

### ISSUE THREAD

**Issue by Karthik-Ra0** [microsoft/EntraExporter#38]
Firstly, would like to say this is not really an issue with the exporter. 

I am looking into building a product that takes periodical backups of the data from the Azure Active Directory. Is there a way we can take a consistent backup of the entire Azure Active Directory i.e a backup with the logical relationships snapshotted consistently at a point in time. The graph APIs only provides a way to get Users, groups, roles in separate Rest API calls which could lead to some inconsistency. Or is there a way to put the active directory in a maintenance mode for the period of the backup to not take any write requests ?

**Comment by merill** [comment]
Sorry, unfortunately the Graph API is the best we have at the moment.
