### ISSUE TITLE
Conditional Access Policy: Multiple Grants -  Null value

### ISSUE THREAD

**Issue by BT-ITA-Olaf** [microsoft/EntraExporter#39]
Hi all,

When we are using the exporter to export conditional access policies, the grant controls are null values when multiple values are selected in the portal. 

So when we select two grant controls, for example:

1. Require device to be marked as compliant
2. Require approved client app

the value of the variable "builtInControls" in the JSON equals 'null'. 

Is there a way to obtain both controls? 

Thanks in advance.

**Comment by merill** [comment]
Thanks. I've found the root cause for this. Will release a fix soon.

**Comment by BT-ITA-Olaf** [comment]
Hi Merill,

Thank you for helping us. Good to hear that you have found the cause. Any idea when you will be able to release the fix?

**Comment by BT-ITA-Olaf** [comment]
Hi,

Is there any update on this topic? Or might there be a way to assist?

**Comment by BT-ITA-Olaf** [comment]
Hi Merill,

We are still facing the same issue. Is there any update on this?

**Comment by merill** [comment]
My sincere apologies for the delay in this @BT-ITA-Olaf 

The good news is that it has been fixed. You will need to get the latest version now renamed to EntraExporter.
