### ISSUE TITLE
Enhancement: Exclude Members from Dynamic Groups 

### ISSUE THREAD

**Issue by roflrolle** [microsoft/EntraExporter#40]
For our usecase it is not necessary to have the members for every dynamic group in the backup.
It might be relevant for others too.
The dynamic membership rule is enough to view as the dynamic members might change very frequently.

Perhaps it would be a good idea to enable a switch like "-ExcludeDynamicGroupMembers" where we only have the owners and group properties exported.

The possibility to leave the members out will also reduce the runtime of the script

**Comment by merill** [comment]
Excluding members of dynamic groups is the default now. It didn't make sense to spend cycles downloading user objects of dynamic groups.
