### ISSUE TITLE
403 Forbidden when used in PowerShell Core 7.3.7 (Azure DevOps pipeline)

### ISSUE THREAD

**Issue by ztrhgf** [microsoft/EntraExporter#57]
I've created an Azure application, grant it a "Global reader" role + all graph permission needed.

If used in PowerShell 5.1 on my local computer like:
```
$ApplicationId = "appid"
$SecuredPassword = "password"
$tenantID = "tenant.onmicrosoft.com"

$SecuredPasswordPassword = ConvertTo-SecureString -String $SecuredPassword -AsPlainText -Force
$ClientSecretCredential = New-Object `
    -TypeName System.Management.Automation.PSCredential `
    -ArgumentList $ApplicationId, $SecuredPasswordPassword

Connect-MgGraph -TenantId $tenantID -ClientSecretCredential $ClientSecretCredential -NoWelcome

Export-Entra "C:\prod-backup" -All
```
everything works fine and Azure settings are backed up. If the same code is called inside the Azure DevOps pipeline, it throws an error 
![err3](https://github.com/microsoft/EntraExporter/assets/2930419/9276ccca-fca1-4bdb-a9f9-46e7cb1c7ff2)

Any ideas what is going on? The same Graph and EntraExported modules version are used.

**Comment by kenxukordia** [comment]
I am having the same issue with PS 7, I used graph explorer to call the same endpoint and received same error.

This will work
https://graph.microsoft.com/beta/organization/tenantID

When you add settings to the end like below. it starts erroring out
https://graph.microsoft.com/beta/organization/tenantID/settings

I am now thinking that "settings" is not a valid after / as per graphexplorer

![Screenshot 2023-11-09 at 12 55 27](https://github.com/microsoft/EntraExporter/assets/142298073/63aa12a0-5d5f-4d52-a446-f2ea54e2c5ea)

**Comment by merill** [comment]
This has been fixed now. Please update to the latest version
