### ISSUE TITLE
Required Permissions for Access Review Export

### ISSUE THREAD

**Issue by DenizSe** [microsoft/EntraExporter#6]
Hello,

i encountered the following error during a full export:

Export-AzureAD -Path 'C:\AzureADBackup\' -all

Application was consented with all permissions and i got the error during the AccessReview Export.

```
 IdentityGovernance/AccessReviews
    842169fe-e1b7-4ce9-98b6-6a9db02eec6b
Invoke-MgGraphRequest : GET https://graph.microsoft.com/beta/accessReviews?$filter=(businessFlowTemplateId+eq+%27842169
fe-e1b7-4ce9-98b6-6a9db02eec6b%27)
HTTP/1.1 403 Forbidden
```
Workaround:

After some reverse Engineering, i found that my user account needs to have Identity Governance Administrator to be able to successfully export the access Reviews.

**Comment by merill** [comment]
Thanks for the feedback @DenizSe. We will reach out to the team and let them know about this issue.

**Comment by sopelt** [comment]
Any update on this @merill ?

**Comment by SamErde** [comment]
Have you tried using application permissions instead of delegated (user) permissions?

![image](https://user-images.githubusercontent.com/20478745/174780843-99878ad6-4b2b-4a7d-9888-77477a02a087.png)

**Comment by merill** [comment]
This permission issue has now been resolved.
