### ISSUE TITLE
QUESTION: Is it possible to authenticate using managed identity in the Azure pipeline?

### ISSUE THREAD

**Issue by ztrhgf** [microsoft/EntraExporter#63]
I am trying to figure out whether it is possible to use "[workload identity federation service connection](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-a-new-workload-identity-federation-service-connection)" to authenticate instead of providing secret/certificate?

Does anyone have any experience with this topic?

**Comment by berchouinard** [comment]
I have used the yaml file from this website https://doitpsway.com/how-to-easily-backup-your-azure-environment-using-entraexporter-and-azure-devops-pipeline and modified it to add a task to it, refer to this website https://gotoguy.blog/2023/09/15/connect-to-microsoft-graph-in-azure-devops-pipelines-using-workload-identity-federation/ for the workload identity federation and the task to make it work.
